module App.Etc.Style exposing (..)

import Css exposing (..)


-- Palette generated by Material Palette - materialpalette.com/indigo/green


darkPrimaryColor =
    hex "303F9F"


primaryColor =
    hex "3F51B5"


lightPrimaryColor =
    hex "C5CAE9"


textPrimaryColor =
    hex "FFFFFF"


accentColor =
    hex "4CAF50"


primaryTextColor =
    hex "212121"


secondaryTextColor =
    hex "757575"


dividerColor =
    hex "BDBDBD"


screen_xx_small =
    em (320 / 16)


screen_x_small =
    em (480 / 16)


screen_small =
    em (640 / 16)


screen_medium =
    em (768 / 16)


screen_large =
    em (1080 / 16)


screen_x_large =
    em (1440 / 16)


screen_xx_large =
    em (2160 / 16)


font_xx_small =
    Css.rem (10 / 16)


font_x_small =
    Css.rem (12 / 16)


font_small =
    Css.rem (14 / 16)


font_medium =
    Css.rem (16 / 16)


font_large =
    Css.rem (20 / 16)


font_x_large =
    Css.rem (24 / 16)


font_xx_large =
    Css.rem (32 / 16)
